name: Deploy to Master

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_type: "json-extended"
          webhook_url: ${{ secrets.WEBHOOK_URL_MASTER }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET_MASTER }}